console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 4
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # Segment for the current directory path
  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.options]
      style = 'full'

  # Segment for Python virtual environment
  [[blocks.segments]]
    template = ' <#EEDC82>via</>   {{ if .Venv }}{{ .Venv }} {{ end }}({{ .Full }})'
    foreground = '#3498DB'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.options]
      display_mode = 'environment' # Recommended to show only when in a venv
      fetch_virtual_env = true

  # Segment for Node.js projects (including React, Vue, etc.)
  [[blocks.segments]]
    template = ' <#EEDC82>via</>   ({{ .Full }})'
    foreground = '#4CA84C'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.options]
      display_mode = 'files' # Show when package.json, etc., is found
      fetch_package_manager = true

  # Segment for Git status
  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}  {{ end }}{{ if gt .Behind 0 }} ⇣{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }} ⇡{{ .Ahead }}{{ end }}'
    foreground = 'p:grey'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.options]
      branch_icon = ' '
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  # Segment for command execution time
  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.options]
      threshold = 1000 # Only show if execution time > 1s

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # The main prompt symbol
  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']
