# The Graphite / Void Palette

# The Void (Pure Black)
background              #000000
# The Signal (High Contrast White/Grey)
foreground              #EBDBB2
selection_foreground    #000000
selection_background    #B0B0B0

# Cursor colors
cursor                  #EBDBB2
cursor_text_color       #000000

# URL underline color
url_color               #0087BD

# Borders (Dark Grey to match Graphite Window Borders)
active_border_color     #666666
inactive_border_color   #333333
bell_border_color       #EBDBB2

# Tab bar colors (Minimalist)
active_tab_foreground   #000000
active_tab_background   #B0B0B0
inactive_tab_foreground #666666
inactive_tab_background #000000
tab_bar_background      #000000

# blue
color4  #61AFEF
color12 #61AFEF